courses=[BCom,BTech,BMS,AA,AAA,AE,AS,AGS,ASN,AF,AT,AAS,AAT,ABS,AAT,ABS,ABA,
         AES,ADN,AET,AFA,APE,AIT,AOS,ASPT-APT,APS,BArch,BA,AB,BS,BSc,SB,ScB,
         BAA,BAAS,BaAppSc(IT),BDes,BEng,BE,BSE,BESc,BSEng,BASc,BSc(Eng),AMIE,
         GradIETE,BSBA,BSET,BIBE,BBA,BIBE,BFA,BBus,BMOS,BBusSc,B.Acc,B.Compt,
         BEc, BEconSc,BAOM,BCompSc,BComp,BCA,BBIS,BSc,BMedSci,BMedBiol,
         BSPH,BN,BNSc,BScN,BSN,BNurs,BSN,BHSc,BHS,BKin,BHK,BSc(Kin),BAT,BAvn,
         BD,BTheol,BRE,BRS,BF&TV,BIS,BAJ,BLArch,B.L.A,BGS,BSc,BAS,BPS,B.Lib,B.L.I.S,
         BM,BA in Music,BME,PhB,BAPSY,BSE, BS in Ed,BScEd,BASc,BSL,BSocSc,BTL,BSW,BTS,
         BMath,BPAPM,BURP,MAcc,MAS,MEcon,MArch,MASc,MA,MAT,ALM,MLA,MBA,MBI,MChem,MCom,
         MCA,MCJ,MDes,MDiv,MEcon,MEd,MEnt,MEng,MEM,MFin,MFA,MHS,MHA,MILR,MIS,MSIT,MJur,
         MPS,MPA,MPAff,MPH,MPP,MRb,MSM,MSE,MFin,HRD,MSIS,MSMIS,MSN,MSPM,MSM,MSL,SCM,MST,
         MSW,MSSc,ChM,MSt,ThM,MTS,MVSC
     ]